services:
  - type: web
    name: sygnasis
    env: python
    startCommand: "./start.sh"
    preDeployCommand: "python manage.py migrate"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "sygnasis.onrender.com"
      - key: DB_NAME
        fromDatabase:
          name: sygnasis-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: sygnasis-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sygnasis-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: sygnasis-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sygnasis-db
          property: port

databases:
  - name: sygnasis-db
    databaseName: sygnasis
    user: sygnasis_user
